### PR TITLE
use prop-types

### PR DESCRIPTION
**Pull request by warrenc5**

### CODE REVIEW

**Comment by ryanbagwell** [comment]
👍

**Comment by ryanbagwell** [comment]
@cameronbourke can this be merged?

**Comment by markmssd** [comment]
@cameronbourke :) Great little library you got there, but will be unusable without this PR...

**Comment by markmssd** [comment]
Thanks @cameronbourke ! Can you please release a new npm version when you can? :)

**Comment by cameronbourke** [comment]
@markmssd All done and dusted! Please let me know if have any issues installing `v1.1.0`!

**Pull request merged**
