### PR TITLE
Added the className prop for styled-components/emotion compatibility

### PR DESCRIPTION
**Pull request by smerth**
Hi there,  I have added the `className` prop to the component.  That should make it compatible with styled-components, emotion and theme-ui...  Thanks for the great component!

### CODE REVIEW

**Review by cameronbourke — APPROVED** [review]
@smerth Thanks so much for opening this PR! 🎉I appreciate the effort. This now closes #14.

**Comment by Fi1osof** [comment]
@cameronbourke please, publich new release into https://www.npmjs.com
Thanks!

**Comment by cameronbourke** [comment]
@Fi1osof hey! I'm planning on doing it today!

**Comment by Fi1osof** [comment]
@cameronbourke thanks!

**Comment by cameronbourke** [comment]
@Fi1osof @smerth hey, thanks again for your work on this! I just published `v1.2.0` to npm :)

**Pull request merged**
